services:
  - type: web
    name: clario-rag-chatbot
    runtime: docker
    dockerfilePath: ./rag-chatbot-free-tier/rag-chatbot/Dockerfile
    dockerContext: ./rag-chatbot-free-tier/rag-chatbot
    plan: free
    region: oregon
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: CHUNK_SIZE
        value: "800"
      - key: CHUNK_OVERLAP
        value: "150"
      - key: TOP_K_RESULTS
        value: "5"
      - key: LLM_MODEL
        value: "gemini-2.5-flash"
      - key: EMBED_MODEL
        value: "gemini-embedding-001"
